version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: springboot_mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: sanskar@06
      MYSQL_ROOT_PASSWORD: sanskar@06
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-network

volumes:
  mysql_data:

networks:
  springboot-network:
    driver: bridge
